
[assembly: System.Reflection.AssemblyProduct("Hprose 1.3 for .NET Framework 2.0")]
[assembly: System.Reflection.AssemblyTitle("Hprose.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.dll")]
[assembly: System.Reflection.AssemblyVersion("2.0.50727.3607")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.50727.3607")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.2.0")]
[assembly: System.Reflection.AssemblyCompany("HPRFC Software Co.,Ltd.")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 HPRFC Software Co.,Ltd. All rights reserved.")]
