[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyProduct("Hprose 1.3 for .NET Framework 1.0")]
[assembly: System.Reflection.AssemblyTitle("Hprose.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.dll")]
[assembly: System.Reflection.AssemblyVersion("1.0.3705.6018")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.3705.6018")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.1.0")]
[assembly: System.Reflection.AssemblyCompany("http://www.hprose.com")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 http://www.hprose.com, All rights reserved.")]
