
[assembly: System.Reflection.AssemblyProduct("Hprose Client 1.3 for Silverlight 3")]
[assembly: System.Reflection.AssemblyTitle("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyVersion("3.0.40818.0")]
[assembly: System.Reflection.AssemblyFileVersion("3.0.40818.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.3.0")]
[assembly: System.Reflection.AssemblyCompany("HPRFC Software Co.,Ltd.")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 HPRFC Software Co.,Ltd. All rights reserved.")]
