[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyProduct("Hprose Client 1.3 for .NET Framework 1.1")]
[assembly: System.Reflection.AssemblyTitle("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyVersion("1.1.4322.2032")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.4322.2032")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.1.1")]
[assembly: System.Reflection.AssemblyCompany("http://www.hprose.com")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 http://www.hprose.com, All rights reserved.")]
