
[assembly: System.Reflection.AssemblyProduct("Hprose Client 1.3 for Silverlight 5")]
[assembly: System.Reflection.AssemblyTitle("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.Client.dll")]
[assembly: System.Reflection.AssemblyVersion("5.0.61118.0")]
[assembly: System.Reflection.AssemblyFileVersion("5.0.61118.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.5.0")]
[assembly: System.Reflection.AssemblyCompany("http://www.hprose.com")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 http://www.hprose.com, All rights reserved.")]
