
[assembly: System.Reflection.AssemblyProduct("Hprose 1.3 for .NET Framework 1.1")]
[assembly: System.Reflection.AssemblyTitle("Hprose.dll")]
[assembly: System.Reflection.AssemblyDescription("Hprose.dll")]
[assembly: System.Reflection.AssemblyDefaultAlias("Hprose.dll")]
[assembly: System.Reflection.AssemblyVersion("1.1.4322.2032")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.4322.2032")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.1.1")]
[assembly: System.Reflection.AssemblyCompany("HPRFC Software Co.,Ltd.")]
[assembly: System.Reflection.AssemblyCopyright("\x00a9 HPRFC Software Co.,Ltd. All rights reserved.")]
